import fs from "fs-extra";
import path from "path";
import { select } from "@inquirer/prompts";
import { GeneratedFiles, GeneratedFile } from "../generator/index.js";
import { logger } from "../utils/logger.js";

const HEADER = "# Generated by Claude Toad — Review before use\n\n";

export interface WriteOptions {
  force?: boolean;
  dryRun?: boolean;
}

export async function writeFiles(
  projectPath: string,
  files: GeneratedFiles,
  options: WriteOptions = {}
): Promise<string[]> {
  const claudeDir = path.join(projectPath, ".claude");
  const writtenFiles: string[] = [];

  // Handle existing .claude/ directory
  if (await fs.pathExists(claudeDir)) {
    if (!options.force && !options.dryRun) {
      const action = await select({
        message: ".claude/ directory already exists. What do you want to do?",
        choices: [
          { name: "Overwrite (backup existing to .claude.backup/)", value: "overwrite" },
          { name: "Merge (keep existing files, overwrite matching)", value: "merge" },
          { name: "Cancel", value: "cancel" },
        ],
      });

      if (action === "cancel") {
        logger.info("Cancelled. No files written.");
        return [];
      }

      if (action === "overwrite") {
        const backupDir = path.join(projectPath, ".claude.backup");
        await fs.remove(backupDir);
        await fs.copy(claudeDir, backupDir);
        await fs.remove(claudeDir);
        logger.info("Backed up existing .claude/ to .claude.backup/");
      }
      // merge: just proceed, files will be overwritten individually
    } else if (options.force) {
      const backupDir = path.join(projectPath, ".claude.backup");
      await fs.remove(backupDir);
      await fs.copy(claudeDir, backupDir);
      await fs.remove(claudeDir);
    }
  }

  if (options.dryRun) {
    logger.blank();
    logger.log("=== DRY RUN — No files written ===");
    logger.blank();
    logger.log("--- CLAUDE.md ---");
    logger.log(files.claudeMd);
    logger.blank();
    for (const skill of files.skills) {
      logger.log(`--- ${skill.path} ---`);
      logger.log(skill.content);
      logger.blank();
    }
    for (const agent of files.agents) {
      logger.log(`--- ${agent.path} ---`);
      logger.log(agent.content);
      logger.blank();
    }
    for (const cmd of files.commands) {
      logger.log(`--- ${cmd.path} ---`);
      logger.log(cmd.content);
      logger.blank();
    }
    logger.log("--- settings.json ---");
    logger.log(files.settings);
    if (files.mcp) {
      logger.blank();
      logger.log("--- .mcp.json ---");
      logger.log(files.mcp);
    }
    return [];
  }

  // Write CLAUDE.md
  await writeFile(claudeDir, "CLAUDE.md", HEADER + files.claudeMd);
  writtenFiles.push(".claude/CLAUDE.md");

  // Write skills
  for (const skill of files.skills) {
    await writeFile(claudeDir, skill.path, HEADER + skill.content);
    writtenFiles.push(`.claude/${skill.path}`);
  }

  // Write agents
  for (const agent of files.agents) {
    await writeFile(claudeDir, agent.path, HEADER + agent.content);
    writtenFiles.push(`.claude/${agent.path}`);
  }

  // Write commands
  for (const cmd of files.commands) {
    await writeFile(claudeDir, cmd.path, HEADER + cmd.content);
    writtenFiles.push(`.claude/${cmd.path}`);
  }

  // Write settings.json (no header — it's JSON)
  await writeFile(claudeDir, "settings.json", files.settings);
  writtenFiles.push(".claude/settings.json");

  // Write .mcp.json to project root (not inside .claude/)
  if (files.mcp) {
    const mcpPath = path.join(projectPath, ".mcp.json");
    await fs.writeFile(mcpPath, files.mcp, "utf-8");
    writtenFiles.push(".mcp.json");
  }

  return writtenFiles;
}

async function writeFile(
  baseDir: string,
  relativePath: string,
  content: string
): Promise<void> {
  const fullPath = path.join(baseDir, relativePath);
  await fs.ensureDir(path.dirname(fullPath));
  await fs.writeFile(fullPath, content, "utf-8");
}
